language: python
python:
  - "2.7"
env:
  global:
  - DJANGO_SETTINGS_MODULE="mousedb.travis_settings"
  - PYTHONPATH="/home/travis/build/BridgesLab/mousedb"
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip install coveralls
  - pip install -r requirements.txt --use-mirrors
#before_script:
script:
  - python manage.py test
  - coverage run --source='.' manage.py test
after_success:
    coveralls
