language: python
python:
  - "2.6"
  - "2.7"
env:
  global:
  - DJANGO_SETTINGS_MODULE="mousedb.travis_settings"
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
# command to install dependencies
install:
  - pip install coveralls
  - pip install -r requirements.txt --use-mirrors
#before_script:
#  - python manage.py syncdb --noinput
script:
  - python manage.py test
  - coverage run --source='.' manage.py test
after_success:
    coveralls
