language: python
python:
  - "2.8"
  - "3.4"
  - "3.5"
env:
  global:
  - DJANGO_SETTINGS_MODULE="mousedb.travis_settings"
# command to install dependencies
install:
  - pip install coveralls
  - pip install -r requirements.txt --use-mirrors
#before_script:
script:
  - python manage.py test
  - coverage run --source='.' manage.py test
after_success:
    coveralls
