language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "nightly"
env:
  - DJANGO_VERSION=1.9.7
  - DJANGO_VERSION=1.10b1
  global:
  - DJANGO_SETTINGS_MODULE="travis_settings"
  - PYTHONPATH="/home/travis/build/BridgesLab/mousedb"
# command to install dependencies
install:
  - pip install coveralls
  - pip install -r requirements.txt --use-mirrors
#before_script:
script:
  - python manage.py test
  - coverage run --source='.' manage.py test
after_success:
    coveralls
